### ISSUE TITLE
Unable to download models

### ISSUE THREAD

**Issue by Mansi-1** [Ashish-Surve/Comparsion_Segmentation_models#2]
While starting the docker container, the backend container terminates with the following error:
`Traceback (most recent call last):
  File "main.py", line 17, in <module>
    import inference
  File "/app/inference.py", line 31, in <module>
    modelUnet.load_weights(model_path)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/network.py", line 1221, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)`

And the UI of the application shows the following error:
`ConnectionError: HTTPConnectionPool(host='backend', port=8080): Max retries exceeded with url: /unet (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f599ffd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))` 

Am I missing something while starting the conatiner?

**Comment by Ashish-Surve** [comment]
It seems like the models haven't been downloaded on your system. 
Possible Solutions:
1. Install Lfs and try to clone again.
2. Manually download and place the models.

this should help you run the project in one line.

**Comment by Ashish-Surve** [comment]
Model wasn't downloaded.
Above recommendations solved the issue.
